using System.Text.Json;
using System.Text.Json.Serialization;

namespace AltStableCompanion.Core;

/// <summary>One manifest line's worth: what the Roster reads to draw a cutout.</summary>
public sealed record ManifestEntry(string Key, string? Guid, string FileName, int W, int H, int TexW, int TexH,
    double? NativeW, double? NativeH);

/// <summary>
/// The generated <c>Interface\AddOns\AltStableCutouts</c> addon: TGAs and their JSON sidecars
/// under <c>Cutouts\</c>, the .toc, and CutoutManifest.lua. Ported from Update-Cutouts.ps1.
///
/// A folder of its own because a Lua file dropped into AltStable\ is never loaded unless the
/// committed .toc lists it, and a deploy would overwrite it. The client only discovers a NEW
/// addon folder at startup, which is why <see cref="EnsureToc"/> reports creating it.
/// </summary>
public sealed class CutoutFolder(string addonDir)
{
    public const string AddonName = "AltStableCutouts";

    public const string Toc = """
        ## Interface: 16001
        ## Title: AltStable Cutouts
        ## Notes: Character portraits captured locally by AltStable. GENERATED by AltStable Companion - delete this folder to start over.
        ## IconTexture: 8197123
        ## Dependencies: AltStable
        ## Author: generated
        ## Version: 1

        CutoutManifest.lua
        """;

    private static readonly JsonSerializerOptions Json = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNameCaseInsensitive = true,
    };

    public string AddonDir { get; } = addonDir;
    public string CutoutsDir => Path.Combine(AddonDir, "Cutouts");
    public string TocPath => Path.Combine(AddonDir, AddonName + ".toc");
    public string ManifestPath => Path.Combine(AddonDir, "CutoutManifest.lua");
    public bool Exists => Directory.Exists(AddonDir);

    /// <summary>
    /// Write the .toc when it differs - "once and left alone" meant a change here could never
    /// reach an existing install. Returns true when the ADDON was newly created: the player
    /// then has to restart the game once, because /reload does not find new addons.
    ///
    /// New is judged by the .toc, as Update-Cutouts.ps1 judged it, not by the folder: a folder
    /// without a .toc (a first run cut short, a .toc deleted by hand) is an addon the client
    /// has not discovered either.
    /// </summary>
    public bool EnsureToc()
    {
        var created = !File.Exists(TocPath);
        Directory.CreateDirectory(CutoutsDir);
        var current = created ? null : File.ReadAllText(TocPath);
        if (current is null || Normalise(current) != Normalise(Toc))
        {
            WriteAtomic(TocPath, Toc.ReplaceLineEndings("\r\n") + "\r\n");
        }
        return created;
    }

    public void WriteCutout(string fileBase, RgbaImage canvas, CutoutMeta meta)
    {
        Directory.CreateDirectory(CutoutsDir);
        var tga = Path.Combine(CutoutsDir, fileBase + ".tga");
        var tmp = tga + ".tmp";
        TgaCodec.Write(tmp, canvas);
        File.Move(tmp, tga, overwrite: true);
        WriteAtomic(Path.Combine(CutoutsDir, fileBase + ".json"), JsonSerializer.Serialize(Sidecar.From(meta), Json));
    }

    /// <summary>The sidecar of a cutout, or null when it has none or it does not parse.</summary>
    public CutoutMeta? ReadMeta(string fileBase)
    {
        var path = Path.Combine(CutoutsDir, fileBase + ".json");
        if (!File.Exists(path)) return null;
        try
        {
            return JsonSerializer.Deserialize<Sidecar>(File.ReadAllText(path), Json)?.ToMeta();
        }
        catch (Exception ex) when (ex is JsonException or IOException or UnauthorizedAccessException)
        {
            return null;
        }
    }

    /// <summary>The GUID that owns a file base, per its sidecar - for choosing a namesake's file name.</summary>
    public string? OwnerOf(string fileBase) => ReadMeta(fileBase)?.Guid;

    /// <summary>
    /// The file base holding this character's portrait, if any. When several files carry the
    /// GUID - make-cutout.py named files by the CURRENT name, so a renamed character leaves its
    /// old file behind - it is the one from the newest capture, then the first by name. The
    /// manifest lists that file and no other, so what is written next is what is drawn.
    /// </summary>
    public string? FileBaseOf(string guid)
    {
        if (!Directory.Exists(CutoutsDir)) return null;
        string? best = null;
        long? bestEpoch = null;
        foreach (var json in Directory.EnumerateFiles(CutoutsDir, "*.json").Order(StringComparer.Ordinal))
        {
            var fileBase = Path.GetFileNameWithoutExtension(json);
            if (ReadMeta(fileBase) is not { } meta || meta.Guid != guid) continue;
            if (!File.Exists(Path.Combine(CutoutsDir, fileBase + ".tga"))) continue;
            if (best is null || (meta.Epoch ?? long.MinValue) > (bestEpoch ?? long.MinValue))
            {
                best = fileBase;
                bestEpoch = meta.Epoch;
            }
        }
        return best;
    }

    /// <summary>
    /// The screenshots the cutouts on disk were made from, by file name: every sidecar's, not
    /// only the ones some capture in the records still points at. A cutout keeps its claim to
    /// its sources for as long as it exists - whatever its character has captured since.
    /// </summary>
    public IReadOnlyList<string> RecordedShots()
    {
        var names = new List<string>();
        if (!Directory.Exists(CutoutsDir)) return names;
        foreach (var json in Directory.EnumerateFiles(CutoutsDir, "*.json").Order(StringComparer.Ordinal))
        {
            var fileBase = Path.GetFileNameWithoutExtension(json);
            if (!File.Exists(Path.Combine(CutoutsDir, fileBase + ".tga"))) continue;
            // A name, never a path: the sidecar is a file anyone can edit.
            names.AddRange((ReadMeta(fileBase)?.Shots ?? [])
                .Where(n => !string.IsNullOrWhiteSpace(n))
                .Select(n => Path.GetFileName(n)));
        }
        return names;
    }

    /// <summary>
    /// One entry per TGA on disk, sorted by file name: from its sidecar, or - for a cutout made
    /// before sidecars existed - from the image itself, with no native size rather than an
    /// invented one. A native size only counts when the sidecar DECLARES its unit and it is not
    /// the full screen: one bogus height halves every other character in the scene.
    ///
    /// Left out, with a warning: a file whose name or GUID cannot be written into Lua as it is
    /// (see <see cref="ManifestWriter"/>), and a second file carrying a GUID another file
    /// already answers for - two entries with one key, and Lua keeps the last.
    /// </summary>
    public IReadOnlyList<ManifestEntry> Inventory(Action<string>? warn = null)
    {
        var entries = new List<ManifestEntry>();
        if (!Directory.Exists(CutoutsDir)) return entries;
        foreach (var tga in Directory.EnumerateFiles(CutoutsDir, "*.tga").Order(StringComparer.Ordinal))
        {
            var fileBase = Path.GetFileNameWithoutExtension(tga);
            var fileName = Path.GetFileName(tga);
            var meta = ReadMeta(fileBase);
            // The key is the GUID, or the file's own name for a cutout that has none.
            if (!ManifestWriter.IsSafeFileName(fileName) || !ManifestWriter.IsSafeKey(meta?.Guid ?? fileBase))
            {
                warn?.Invoke($"{fileName} is not listed: its name or GUID has characters a manifest cannot carry");
                continue;
            }
            if (meta?.Guid is { } guid && FileBaseOf(guid) is { } chosen
                && !string.Equals(chosen, fileBase, StringComparison.OrdinalIgnoreCase))
            {
                warn?.Invoke($"{fileName} is not listed: {chosen}.tga is the same character's newer portrait");
                continue;
            }
            if (meta is not null)
            {
                var native = meta.NativeUnit == "screen" && meta.NativeH is < CutoutConverter.MaxScreenFraction;
                entries.Add(new ManifestEntry(meta.Guid ?? fileBase, meta.Guid, fileName, meta.W, meta.H,
                    meta.TexW, meta.TexH, native ? meta.NativeW : null, native ? meta.NativeH : null));
                continue;
            }
            try
            {
                var img = TgaCodec.Read(tga);
                var box = img.AlphaBounds();
                entries.Add(new ManifestEntry(fileBase, null, fileName, box?.Width ?? img.Width,
                    box?.Height ?? img.Height, img.Width, img.Height, null, null));
            }
            catch (Exception ex) when (ex is IOException or TgaFormatException)
            {
                // Unreadable right now; it will be listed on the next pass.
            }
        }
        return entries;
    }

    /// <summary>
    /// Rebuild the manifest from what is on disk, and write it when its entries changed. An
    /// idle pass writes nothing: every write is a chance to meet the client reading the file
    /// during a /reload. Returns whether it wrote.
    /// </summary>
    public bool WriteManifest(DateTime now, Action<string>? warn = null)
    {
        var lua = ManifestWriter.Render(Inventory(warn), now);
        if (File.Exists(ManifestPath) && ManifestWriter.SameEntries(File.ReadAllText(ManifestPath), lua))
        {
            return false;
        }
        WriteAtomic(ManifestPath, lua);
        return true;
    }

    private static string Normalise(string s) => s.ReplaceLineEndings("\n").Trim();

    private static void WriteAtomic(string path, string content)
    {
        var tmp = path + ".tmp";
        File.WriteAllText(tmp, content);
        File.Move(tmp, path, overwrite: true);
    }

    // The sidecar's JSON shape, which make-cutout.py also writes: lowercase keys as there.
    private sealed class Sidecar
    {
        [JsonPropertyName("w")] public int W { get; set; }
        [JsonPropertyName("h")] public int H { get; set; }
        [JsonPropertyName("texw")] public int TexW { get; set; }
        [JsonPropertyName("texh")] public int TexH { get; set; }
        [JsonPropertyName("nativeW")] public double? NativeW { get; set; }
        [JsonPropertyName("nativeH")] public double? NativeH { get; set; }
        [JsonPropertyName("nativeUnit")] public string? NativeUnit { get; set; }
        [JsonPropertyName("nativePx")] public int[]? NativePx { get; set; }
        [JsonPropertyName("guid")] public string? Guid { get; set; }
        [JsonPropertyName("epoch")] public long? Epoch { get; set; }
        [JsonPropertyName("shots")] public string[]? Shots { get; set; }

        public static Sidecar From(CutoutMeta m) => new()
        {
            W = m.W, H = m.H, TexW = m.TexW, TexH = m.TexH, NativeW = m.NativeW, NativeH = m.NativeH,
            NativeUnit = m.NativeUnit, NativePx = m.NativePx, Guid = m.Guid, Epoch = m.Epoch, Shots = m.Shots,
        };

        public CutoutMeta ToMeta() => new()
        {
            W = W, H = H, TexW = TexW, TexH = TexH, NativeW = NativeW, NativeH = NativeH,
            NativeUnit = NativeUnit, NativePx = NativePx, Guid = Guid, Epoch = Epoch, Shots = Shots,
        };
    }
}
