using System.Globalization;
using System.Text;

namespace AltStableCompanion.Core;

/// <summary>
/// CutoutManifest.lua, the one global the Roster reads (docs/PORTRAIT-CONTRACT.md, section 2).
/// Entries carrying a GUID are keyed by it; older ones keep their name slug. Each line has the
/// exact shape Update-Cutouts.ps1 writes, which is the shape known to load.
/// </summary>
public static class ManifestWriter
{
    public static string Render(IEnumerable<ManifestEntry> entries, DateTime now)
    {
        var sb = new StringBuilder();
        sb.Append("""
            -- CutoutManifest.lua - GENERATED by AltStable Companion
            -- Part of the AltStableCutouts addon, which exists only on this machine.
            --
            -- One entry per character cutout on disk, keyed by the character's GUID (older
            -- entries by name). w/h are the CONTENT size; texw/texh are the power-of-two canvas
            -- the image sits in the top-left of, so the UI can crop back to the figure.
            -- nativeW/nativeH are how much of the SCREEN the capture filled - not a race height.
            -- Regenerated wholesale: delete a TGA to retire a character, do not hand-edit this file.
            --

            """);
        sb.Append("-- Generated ").Append(now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)).Append("\n\n");
        sb.Append("AltStableCutoutManifest = {\n");
        foreach (var e in entries)
        {
            sb.Append("    ['").Append(e.Key).Append("'] = { ");
            if (e.Guid is not null) sb.Append("guid = '").Append(e.Guid).Append("', ");
            sb.Append(@"file = [[Interface\AddOns\").Append(CutoutFolder.AddonName).Append(@"\Cutouts\")
              .Append(e.FileName).Append("]], ");
            sb.Append(CultureInfo.InvariantCulture, $"w = {e.W}, h = {e.H}, texw = {e.TexW}, texh = {e.TexH}");
            if (e.NativeW is { } nw && e.NativeH is { } nh)
            {
                sb.Append(", nativeW = ").Append(nw.ToString(CultureInfo.InvariantCulture))
                  .Append(", nativeH = ").Append(nh.ToString(CultureInfo.InvariantCulture));
            }
            sb.Append(" },\n");
        }
        sb.Append("}\n");
        return sb.ToString().ReplaceLineEndings("\r\n");
    }
}
