using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace AltStableCompanion.Core;

/// <summary>
/// CutoutManifest.lua, the one global the Roster reads (docs/PORTRAIT-CONTRACT.md, section 2).
/// Entries carrying a GUID are keyed by it; older ones keep their name slug. Each line has the
/// exact shape Update-Cutouts.ps1 writes, which is the shape known to load.
///
/// Keys, GUIDs and file names are written between quotes and long brackets as they are, so
/// only ones that cannot end the quoting are written at all: a TGA named <c>o'brien.tga</c>
/// would be a syntax error that loses EVERY portrait, and a GUID is text from a file anyone
/// can edit. Everything this app and the converters before it name passes; what does not is
/// left out of the manifest, not escaped into a shape nobody has seen load.
/// </summary>
public static partial class ManifestWriter
{
    private const string GeneratedPrefix = "-- Generated ";

    /// <summary>A GUID or a legacy key: letters, digits, "-" and "_".</summary>
    public static bool IsSafeKey(string? s) => s is not null && SafeKey().IsMatch(s);

    /// <summary>A file name: the same, and dots.</summary>
    public static bool IsSafeFileName(string? s) => s is not null && SafeFileName().IsMatch(s);

    public static bool IsSafe(ManifestEntry e) =>
        IsSafeKey(e.Key) && (e.Guid is null || IsSafeKey(e.Guid)) && IsSafeFileName(e.FileName);

    /// <summary>
    /// Do two manifests list the same entries? The "Generated" line is the only one allowed to
    /// differ - it changes every second, and is no reason to write the file again.
    /// </summary>
    public static bool SameEntries(string a, string b) => WithoutDate(a) == WithoutDate(b);

    private static string WithoutDate(string lua) => string.Join('\n',
        lua.ReplaceLineEndings("\n").Split('\n').Where(l => !l.StartsWith(GeneratedPrefix, StringComparison.Ordinal)));

    public static string Render(IEnumerable<ManifestEntry> entries, DateTime now)
    {
        var sb = new StringBuilder();
        sb.Append("""
            -- CutoutManifest.lua - GENERATED by AltStable Companion
            -- Part of the AltStableCutouts addon, which exists only on this machine.
            --
            -- One entry per character cutout on disk, keyed by the character's GUID (older
            -- entries by name). w/h are the CONTENT size; texw/texh are the power-of-two canvas
            -- the image sits in the top-left of, so the UI can crop back to the figure.
            -- nativeW/nativeH are how much of the SCREEN the capture filled - not a race height.
            -- Regenerated wholesale: delete a TGA to retire a character, do not hand-edit this file.
            --

            """);
        sb.Append(GeneratedPrefix).Append(now.ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture)).Append("\n\n");
        sb.Append("AltStableCutoutManifest = {\n");
        foreach (var e in entries.Where(IsSafe))
        {
            sb.Append("    ['").Append(e.Key).Append("'] = { ");
            if (e.Guid is not null) sb.Append("guid = '").Append(e.Guid).Append("', ");
            sb.Append(@"file = [[Interface\AddOns\").Append(CutoutFolder.AddonName).Append(@"\Cutouts\")
              .Append(e.FileName).Append("]], ");
            sb.Append(CultureInfo.InvariantCulture, $"w = {e.W}, h = {e.H}, texw = {e.TexW}, texh = {e.TexH}");
            if (e.NativeW is { } nw && e.NativeH is { } nh)
            {
                sb.Append(", nativeW = ").Append(nw.ToString(CultureInfo.InvariantCulture))
                  .Append(", nativeH = ").Append(nh.ToString(CultureInfo.InvariantCulture));
            }
            sb.Append(" },\n");
        }
        sb.Append("}\n");
        return sb.ToString().ReplaceLineEndings("\r\n");
    }

    [GeneratedRegex(@"^[A-Za-z0-9_-]+\z")]
    private static partial Regex SafeKey();

    [GeneratedRegex(@"^[A-Za-z0-9_.-]+\z")]
    private static partial Regex SafeFileName();
}
